document.write('<div class="topnav">');
document.write('<a class="active" href="..\\home\\almanac.htm">Home</a>');
document.write('<a href="..\\locomotives\\locomotives.htm">Locomotives</a>');
document.write('<a href="..\\clock\\clock.htm">Clock</a>');
document.write('<a href="..\\chessboard\\chessboard.htm">Chess</a>');
document.write('<a href="..\\connect4\\connect4.htm">Connect 4</a>');
document.write('<a href="..\\boggle4\\boggle4.htm">Boggle 4*4</a>');
document.write('<a href="..\\calculator\\calculator.htm">Calculator</a>');
document.write('<a href="..\\gallery\\gallery.htm">Gallery</a>');
document.write('<a href="..\\barcode\\barcode.htm">Barcodes</a>');
document.write('<a href="..\\sounds\\sounds.html">Sounds</a>');
document.write('<a href="..\\wordle\\wordle.html">Wordle</a>');
document.write('</div>');